_schema: _schema
paths:
  uploads: public/images
  static: public/images
collections_config:
  about:
    path: src/content/about
    name: About
    icon: bolt
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    name: Blog
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  book_demo:
    path: src/content/book-demo
    name: Book Demo
    icon: book
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  changelog:
    path: src/content/changelog
    name: Changelog
    icon: cancel
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  contact:
    path: src/content/contact
    name: Contact
    icon: contacts
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  features:
    path: src/content/features
    name: Features
    icon: gesture
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  homepage:
    path: src/content/homepage
    name: Homepage
    icon: compare
    disable_url: false
    description: ''
    _enabled_editors:
    _inputs:
      left:
        type: image
        cascade: true
      right:
        type: image
        cascade: true
      center:
        type: image
        cascade: true
      images:
        type: image
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  integrations:
    path: src/content/integrations
    name: Integrations
    icon: attractions
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages_1:
    path: src/content/pages
    name: Pages 1
    icon: pages
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pricing:
    path: src/content/pricing
    name: Pricing
    icon: dining
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  sections:
    path: src/content/sections
    name: Sections
    icon: directions
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_config:
    path: src/config
    name: Src Config
    icon: roofing
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
